name: Build Standalone Apps and Release
on:
  workflow_dispatch:   # allow manual trigger
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-15-intel]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies and update Align frames
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build executable
        shell: bash
        run: |
          case "${{ matrix.os }}" in
            macos-*)   ICON="icon/icon.icns" ;;
            windows-*) ICON="icon/icon.ico" ;;
            *)         ICON="icon/icon.png" ;;
          esac
          pyinstaller gui.py --onedir --windowed --noconfirm --name "Mower Tools" --icon="$ICON"

      # zip must be created in this stage with different OS, to preserve executable permissions
      - name: Zip artifact (macOS)
        if: startsWith(matrix.os, 'macos')
        run: cd dist && ditto -c -k --sequesterRsrc --keepParent "Mower Tools.app" "Mower-tools-${{ matrix.os }}.zip"

      - name: Zip artifact (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: cd dist && zip -r "Mower-tools-${{ matrix.os }}.zip" "Mower Tools"

      - name: Zip artifact (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: Compress-Archive -Path "dist/Mower Tools" -DestinationPath "dist/Mower-tools-${{ matrix.os }}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Mower-tools-${{ matrix.os }}
          path: dist/*.zip

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          path: build

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release for ${{ github.ref_name }}" \
            build/**/*.zip
